version: '3.8'
services:

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"

  init-table:
    depends_on:
      - dynamodb-local
    image: garland/aws-cli-docker
    volumes:
      - ~/.aws/:/root/.aws:ro

    environment:
      AWS_PROFILE: gemini
      AWS_DEFAULT_REGION: eu-central-1
      AWS_REGION: eu-central-1

    command: "aws dynamodb create-table \
              --table-name Music \
              --attribute-definitions \
              AttributeName=Artist,AttributeType=S \
              AttributeName=SongTitle,AttributeType=S \
              --key-schema \
              AttributeName=Artist,KeyType=HASH \
              AttributeName=SongTitle,KeyType=RANGE \
               --provisioned-throughput \
              ReadCapacityUnits=2,WriteCapacityUnits=2"
